@include('header')
<?php
print("<center><h2>Your Item has been successfully registered.</h2></center><br>\n");
print("<b>RUBiS has stored the following information about your item:</b><br><p>\n");
print("<TABLE>\n");
empty($item['description']) ? $desc = 'no description' : $desc = $item['description'];
print("<TR><TD>Name<TD>".$item['name']."\n");
print("<TR><TD>Description<TD>$desc\n");
print("<TR><TD>Initial price<TD>".$item['initialPrice']."\n");
print("<TR><TD>ReservePrice<TD>".$item['reservePrice']."\n");
print("<TR><TD>Buy Now<TD>".$item['buyNow']."\n");
print("<TR><TD>Quantity<TD>".$item['quantity']."\n");
print("<TR><TD>Duration<TD>".$item['duration']."\n");
print("</TABLE>\n");
print("<br><b>The following information has been automatically generated by RUBiS:</b><br>\n");
print("<TABLE>\n");
print("<TR><TD>User id<TD>".$item['userId']."\n");
print("<TR><TD>Category id<TD>".$item['categoryId']."\n");
print("</TABLE>\n");
?>
@include('footer')
