@include('header')
<?php
print("<h2>Your registration has been processed successfully</h2><br>\n");
print("<h3>Welcome " . $user->nickname . "</h3>\n");
print("RUBiS has stored the following information about you:<br>\n");
print("First Name : ".$user->firstname."<br>\n");
print("Last Name  : ".$user->lastname."<br>\n");
print("Nick Name  : ".$user->nickname."<br>\n");
print("Email      : ".$user->email."<br>\n");
print("Password   : ".$user->password."<br>\n");
print("Region     : " . $user->region . "<br>\n");
print("<br>The following information has been automatically generated by RUBiS:<br>\n");
print("User id       :".$user->id."<br>\n");
print("Creation date :".$user->creation_date."<br>\n");
print("Rating        :0<br>\n");
print("Balance       :0<br>\n");
?>
@include('footer')